# Setup
title: Danqing Wang
description: Ph.D
url: https://danqing-wang.github.io/
avatar: /danqing.jpeg
paginate: 5
permalink: pretty
cover_image: /bg.jpeg


# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

remote_theme: vszhub/not-pure-poole
# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: vszhub
  card: summary
logo: logo.png
social:
  name: Songzi Vong
  links:
    - https://www.linkedin.com/in/danqing-anna-wang
    - https://twitter.com/annadanqing
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Danqing Wang
  url: https://github.com/danqing-wang
  email: danqing.wang@berkeley.edu

